# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master, pdfbox-3.0.0 ]
  pull_request:
    branches: [ master, pdfbox-3.0.0 ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['8','11']
        
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{matrix.java}}
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu' 
        java-version: ${{matrix.java}}
    - name: Maven -v
      run: mvn -v    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
